# Generated by Django 3.1.5 on 2021-01-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id_category',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_product',
            new_name='id',
        ),
    ]
