# Generated by Django 3.1.5 on 2021-01-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210116_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quant',
            field=models.IntegerField(default=0),
        ),
    ]
